name: Build & Deploy Bodylog Frontend

on:
  push:
    branches:
      - main
    paths:
      - "bodylog-frontend/**"
      - "Dockerfile"
      - ".github/workflows/deploy-frontend.yml"
      - ".dockerignore"
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bodylog-frontend
  CONTAINER_NAME: bodylog-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract short SHA
        id: meta
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build & Push (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: ./bodylog-frontend
          file: ./bodylog-frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.SHORT_SHA }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          set -e
          if [ -z "$EC2_HOST" ]; then
            echo "EC2_HOST is missing"; exit 1
          fi
          if [ -z "$EC2_SSH_KEY_PEM" ]; then
            echo "EC2_SSH_KEY_PEM is missing"; exit 1
          fi
          echo "Secrets OK"
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY_PEM: ${{ secrets.EC2_SSH_KEY_PEM }}

      - name: SSH ping (debug)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_PEM }}
          debug: true
          script_stop: true
          script: |
            echo "SSH connected"
            whoami
            uname -a
            docker --version || echo "docker not found"

      - name: Deploy container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_PEM }}
          script_stop: true
          envs: IMAGE_NAME,CONTAINER_NAME
          script: |
            set -euo pipefail
            IMAGE="${IMAGE_NAME}:latest"
            NAME="${CONTAINER_NAME}"

            echo "[1/3] docker pull ${IMAGE}"
            docker pull "${IMAGE}" || true

            echo "[2/3] stop & remove existing container if any"
            if [ "$(docker ps -aq -f name=^/${NAME}\$)" ]; then
              docker rm -f "${NAME}" || true
            fi

            echo "[3/3] run new container"
            docker run -d \
              --name "${NAME}" \
              -p 3000:3000 \
              --restart unless-stopped \
              "${IMAGE}"

            echo "Deploy finished"
