name: Deploy Frontend to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EC2 (Frontend only)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 프로젝트 경로로 이동 (처음엔 clone 필요)
            if [ ! -d "~/graduate_flutter" ]; then
              git clone https://github.com/sonseongmin/graduate_flutter.git ~/graduate_flutter
            fi

            cd ~/graduate_flutter
            git fetch --all
            git reset --hard origin/main

            # 프론트엔드 도커 빌드
            docker build -t bodylog-frontend ./bodylog-frontend

            # 기존 컨테이너 중지 및 삭제
            docker stop bodylog-frontend || true
            docker rm bodylog-frontend || true

            # 새 컨테이너 실행
            docker run -d -p 3000:3000 --name bodylog-frontend bodylog-frontend